# Generated by Django 3.2.9 on 2022-01-06 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='discussion_Room',
            new_name='Room',
        ),
    ]
