# Generated by Django 3.2.9 on 2021-12-28 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_discussion_discussion_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='discussion_Room',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.room'),
        ),
    ]
