# Generated by Django 3.2.9 on 2022-01-06 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_room_discussion_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topic_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='topic_name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_discussion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.discussion'),
        ),
    ]
