# Generated by Django 3.2.9 on 2021-12-28 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_discussion_discussion_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='Room_description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
