# Generated by Django 3.2.9 on 2021-12-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_remove_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
    ]
