# Generated by Django 3.2.9 on 2022-01-06 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20220106_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topic_discussion',
            new_name='discussion',
        ),
    ]
