# Generated by Django 3.2.9 on 2021-12-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_room_room_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='discussion_description',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
