# Generated by Django 4.0 on 2022-03-07 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_response_response_topic_response_response_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_response',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.response'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.user'),
        ),
    ]
