# Generated by Django 3.2.9 on 2022-01-04 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_discussion_discussion_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrolment',
            unique_together={('student', 'room')},
        ),
    ]
